[phases.setup]
# Установить ffmpeg внутрь контейнера Railway
nixPkgs = ['ffmpeg']

[phases.install]
# Установить Python-зависимости
cmds = ['pip install -r requirements.txt']

[start]
# Стартовая команда для Railway
cmd = 'python bot.py'
