export type Transmission = "Автомат" | "Механика" | "Робот";
export type Fuel = "Бензин" | "Дизель" | "Гибрид" | "Электро";
export type BodyType = "Кроссовер" | "Седан" | "Внедорожник" | "Хэтчбек" | "Универсал" | "Купе";

export type InventoryItem = {
  id: string;
  name: string;
  brand: string;
  year: number;
  mileageKm: number;
  transmission: Transmission;
  fuel: Fuel;
  body: BodyType;
  priceRub: number;
  powerHp: number;
  color: string;
  imageSrc: string;
  featured?: boolean;
  new?: boolean;
};

export const allInventory: InventoryItem[] = [
  {
    id: "a1",
    name: "BMW X5 xDrive40i",
    brand: "BMW",
    year: 2022,
    mileageKm: 24000,
    transmission: "Автомат",
    fuel: "Бензин",
    body: "Кроссовер",
    priceRub: 8990000,
    powerHp: 340,
    color: "Чёрный",
    imageSrc: "/cars/hero-1.svg",
    featured: true,
  },
  {
    id: "a2",
    name: "Mercedes-Benz E 200",
    brand: "Mercedes-Benz",
    year: 2021,
    mileageKm: 18000,
    transmission: "Автомат",
    fuel: "Бензин",
    body: "Седан",
    priceRub: 5790000,
    powerHp: 197,
    color: "Серебристый",
    imageSrc: "/cars/hero-2.svg",
    featured: true,
  },
  {
    id: "a3",
    name: "Audi Q7 45 TDI",
    brand: "Audi",
    year: 2020,
    mileageKm: 46000,
    transmission: "Автомат",
    fuel: "Дизель",
    body: "Внедорожник",
    priceRub: 6390000,
    powerHp: 231,
    color: "Белый",
    imageSrc: "/cars/hero-3.svg",
    featured: true,
  },
  {
    id: "a4",
    name: "Toyota Camry 3.5",
    brand: "Toyota",
    year: 2023,
    mileageKm: 9000,
    transmission: "Автомат",
    fuel: "Бензин",
    body: "Седан",
    priceRub: 4190000,
    powerHp: 249,
    color: "Белый",
    imageSrc: "/cars/hero-2.svg",
    featured: true,
    new: true,
  },
  {
    id: "a5",
    name: "Lexus RX 350",
    brand: "Lexus",
    year: 2022,
    mileageKm: 21000,
    transmission: "Автомат",
    fuel: "Бензин",
    body: "Кроссовер",
    priceRub: 7290000,
    powerHp: 278,
    color: "Тёмно-синий",
    imageSrc: "/cars/hero-1.svg",
    featured: true,
  },
  {
    id: "a6",
    name: "Volkswagen Tiguan",
    brand: "Volkswagen",
    year: 2021,
    mileageKm: 32000,
    transmission: "Робот",
    fuel: "Бензин",
    body: "Кроссовер",
    priceRub: 3090000,
    powerHp: 150,
    color: "Серый",
    imageSrc: "/cars/hero-3.svg",
    featured: true,
  },
  {
    id: "a7",
    name: "Porsche Cayenne S",
    brand: "Porsche",
    year: 2023,
    mileageKm: 5200,
    transmission: "Автомат",
    fuel: "Бензин",
    body: "Внедорожник",
    priceRub: 15900000,
    powerHp: 440,
    color: "Чёрный",
    imageSrc: "/cars/hero-1.svg",
    new: true,
  },
  {
    id: "a8",
    name: "Range Rover Sport SE",
    brand: "Land Rover",
    year: 2022,
    mileageKm: 38000,
    transmission: "Автомат",
    fuel: "Дизель",
    body: "Внедорожник",
    priceRub: 12400000,
    powerHp: 350,
    color: "Белый",
    imageSrc: "/cars/hero-2.svg",
  },
  {
    id: "a9",
    name: "Kia Sportage Luxe",
    brand: "Kia",
    year: 2023,
    mileageKm: 14000,
    transmission: "Робот",
    fuel: "Бензин",
    body: "Кроссовер",
    priceRub: 2890000,
    powerHp: 180,
    color: "Красный",
    imageSrc: "/cars/hero-3.svg",
    new: true,
  },
  {
    id: "a10",
    name: "Hyundai Sonata 2.0",
    brand: "Hyundai",
    year: 2022,
    mileageKm: 27000,
    transmission: "Автомат",
    fuel: "Бензин",
    body: "Седан",
    priceRub: 2490000,
    powerHp: 150,
    color: "Серебристый",
    imageSrc: "/cars/hero-2.svg",
  },
  {
    id: "a11",
    name: "Skoda Octavia 1.8 TSI",
    brand: "Skoda",
    year: 2021,
    mileageKm: 51000,
    transmission: "Робот",
    fuel: "Бензин",
    body: "Универсал",
    priceRub: 2190000,
    powerHp: 180,
    color: "Серый",
    imageSrc: "/cars/hero-3.svg",
  },
  {
    id: "a12",
    name: "Tesla Model 3 LR",
    brand: "Tesla",
    year: 2023,
    mileageKm: 11000,
    transmission: "Автомат",
    fuel: "Электро",
    body: "Седан",
    priceRub: 5990000,
    powerHp: 358,
    color: "Белый",
    imageSrc: "/cars/hero-1.svg",
    new: true,
  },
];

export const featuredInventory = allInventory.filter((c) => c.featured);
